## Configuracion de Spring
spring:
  application:
    name: User
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
## Configuracion de Instancia
server:
  port: 8080